jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: intl, zip, pdo_mysql

      - name: Install dependencies
        run: composer update --optimize-autoloader --no-scripts --no-interaction

      - name: Install filament:assets
        run: php artisan filament:assets

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Authenticate Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

          # Your deployment script here
